language: c
sudo: false
services:
    - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
    global:
        - DISTRO=debian-stable
        - PACKAGE=rpclib-legacy
    matrix:
        - OCAML_VERSION=4.04.2
matrix:
    fast_finish: true
